# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ylwaV5uBnub7LfbaaEwB4aexrt0jIpIW
"""

!pip install pillow numpy

from PIL import Image
import numpy as np
from google.colab import files
uploaded = files.upload()
image_name = list(uploaded.keys())[0]
image = Image.open(image_name)
image_array = np.array(image)
key = int(input("Enter a key (1-255): "))
encrypted = (image_array.astype(np.int16)+key) % 256
encrypted_image = Image.fromarray(encrypted.astype('uint8'))
encrypted_image.save("encrypted.png")
decrypted = (encrypted.astype(np.int16)-key) % 256
decrypted_image = Image.fromarray(decrypted.astype('uint8'))
decrypted_image.save("decrypted.png")
print("Image encrypted successfully!")
print("Image decrypted successfully!")
files.download("encrypted.png")
files.download("decrypted.png")